name: project2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  getwidget: ^2.0.4
  intl: ^0.19.0

  cupertino_icons: ^1.0.2
  scroll_snap_list: ^0.9.1
  rubber: ^1.1.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.24.2
  gap: ^3.0.1
  video_player: ^2.8.1
  chewie: ^1.7.4
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/image/
    - assets/image/cast/
    - assets/image/teaser/
    - assets/video/trailer/

  fonts:
  - family: Open-Sans
    fonts:
      - asset: assets/font/OpenSans-Regular.ttf
        weight: 400
      - asset: assets/font/OpenSans-Light.ttf
        weight: 300
      - asset: assets/font/OpenSans-SemiBold.ttf
        weight: 600
      - asset: assets/font/OpenSans-Bold.ttf
        weight: 700
      - asset: assets/font/OpenSans-ExtraBold.ttf
        weight: 800
#  - family: SVN
#    fonts:
#      - asset: assets/font/SVN-Sigokae.otf
#        weight: 400
#  - family: JosefinSans
#    fonts:
#      - asset: assets/font/JosefinSans-Italic-VariableFont_wght.tff
#        weight: 400
#      - asset: assets/font/JosefinSans-VariableFont_wght.tff
#        weight: 400


